#local_cpu: True
#max_local_cpu_size: 5.0
#max_local_disk_size: 0

#enable_pd: True
#transfer_channel: "nixl"
#pd_role: "sender"
  #pd_proxy_host: "0.0.0.0"
  #pd_proxy_port: 7500
  #pd_buffer_size: 0 #1798963200 # 1GB
  #pd_buffer_device: "hpu"
  #
chunk_size: 2048
  #use_layerwise: True
local_cpu: False
  #local_disk: /workspace/cache_pool
  #max_local_disk_size: 50
  #remote_serde: naive
  #remote_url: "lm://10.239.129.9:8100"
remote_url: "mooncakestore://10.239.129.9:50001/"
max_local_cpu_size: 2  # small local buffer
  #numa_mode: "auto"      # reduce tail latency with multi-NUMA/multi-NIC
pre_caching_hash_algorithm: sha256_cbor_64bit
blocking_timeout_secs: 10

extra_config:
  #  remote_enable_mla_worker_id_as0: true
  use_exists_sync: true
  save_chunk_meta: False  # Enable chunk metadata optimization
  local_hostname: "10.239.129.9"
  metadata_server: etcd://10.239.129.9:2379
  protocol: "tcp"
  device_name: ""
  global_segment_size: 21474836480   # 20 GiB per worker
  master_server_address: "10.239.129.9:50001"
  local_buffer_size: 0    # rely on LMCache local_cpu as the buffer
  mooncake_prefer_local_alloc: true  # prefer local segment if available
