local_cpu: False

enable_pd: True
pd_backend_mode: "sync"
transfer_channel: "nixl"
pd_role: "receiver"
pd_peer_host: "__PD_PEER_HOST__"
pd_peer_init_port: __PD_PEER_INIT_PORT__
pd_peer_alloc_port: __PD_PEER_ALLOC_PORT__
pd_buffer_size: 565175116800
pd_buffer_device: "cpu"
nixl_backends: [UCX]

save_unfull_chunk: false
