local_cpu: False
max_local_cpu_size: 5

enable_pd: True
pd_backend_mode: "sync"
transfer_channel: "nixl"
pd_role: "sender"
pd_proxy_host: __PD_PROXY_HOST__
pd_proxy_port: 7500
pd_buffer_size: 65175116800
pd_buffer_device: "cpu"
nixl_backends: [UCX]

save_unfull_chunk: true
